[package]
name = "subscribe_candlesticks"
version = "0.1.0"
edition = "2021"

[dependencies]
longport = { path = "../../../rust" }
tokio = { version = "1.19", features = ["rt-multi-thread", "macros"] }
